### ISSUE TITLE
Update description criteria too strict

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#202]
I've gotten word that when updating the 1.6.3 fwupd for xps 9370 on LVFS that the tool didn't want to take the changelog as it was provided.  Ideally the same changelog should be usable for both Windows and Linux to keep the lives of people promoting these files easier.

This was the description that was used:
```
Fixes & Enhancements
Fixes:
- Fixed the incorrect Windows operating system logon message that is displayed on the lock screen of Windows.
- Fixed the issue where the characters fail to display on the screen while typing continuously.
- Enabled support for Intel Turbo Boost Technology on I3-8310U processors that was disabled by default.

Enhancements:
- Optimized the battery diagnostics in Dell Enhanced Pre-boot System Assessment (ePSA).
```

This was the error reported:

> Paragraphs is too short, minimum is 12 chars and was 6: [Fixes:]

I think that requirement should be relaxed.

**Comment by hughsie** [comment]
> Ideally the same changelog should be usable for both Windows and Linux to keep the lives of people promoting these files easier

I agree with the sentiment, on the assumption the style guides are similar. In this case the first two lines of the update detail would be rendered like this in GNOME Software when on a smaller displays:

    Fixes & Enhancements Fixes: • Fixed the incorrect Windows operating system...

The `Fixes:` isn't a paragraph, nor is `Fixes & Enhancements` -- it's also completely unnecessary to have the first header as it's labeled everywhere as an update description. The very first line is about a Windows logon message on Linux, which although correct probably isn't the most important part of the update description. What we've been suggesting to vendors is to lead with a line like `This stable release fixes the following issues:` and then `Some new functionality has also been added:` for new features.

What we certainly could do is have two different text boxes for bugfixes and enhancements, and then we can "join" the sections using gettext-style functions. This wouldn't convey the "stable" part of the first line, as for some devices there are development firmwares rather than just having one stream.

So, although it would be easier to just allow OEMs to paste in whatever they already have, research has shown that the better the update description, the more people apply the update. I do think it's worth doing the work, even if it's automatically doing "autocorrections" for things like `Fixes`. I've also got some real feedback from QA teams and end users about the previous quality of the Lenovo update descriptions, something that are much better now the validation is in place.

**Comment by superm1** [comment]
I do like the idea of having two separate check boxes for fixes and enhancements.  I think that could scale well and also helps to enforce style.

At least for Dell we don't do "development"/"unstable" firmware to customers.  FW releases have a very rigid and lengthy development and validation process.  So everything released is "supposed" to be "stable".

**Comment by hughsie** [comment]
We've got a new release details URL now, is that sufficient?

**Comment by hughsie** [comment]
I was talking to people about the split "fixes" and "enhancements" view and the consensus was it would be difficult to partition changes into the two types -- something I find personally when writing release notes for things like the LVFS and fwupd...  I think with the external link to release notes we can expect vendors to use a consistent style on the LVFS. Something like `Fixes & Enhancements Fixes:` or `Enhancemants: None` just looks bad.
