### ISSUE TITLE
ThinkPad T480s firmware update throwing away boot entries

### ISSUE THREAD

**Issue by asanchez1987** [fwupd/lvfs-website#262]
Hi,

I reported a bug to debian-efi and they asked me to open a bug in here since it appears debian maintainers can't do much about it, and then this issue can be forwarded to the appropriate folks at Lenovo and this firmware pulled from LVFS until this is fixed.

The debian bug is this one:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23922770

I'm pasting the problem in here:

The Software Update manager popped up a message for a Thinkpad T480s
firmware update. I proceeded with the Install & Reboot, and after the update finished
and laptop restarted, GRUB completely disappeared. Then I had to follow the
instructions in the following page to reinstall grub:

https://wiki.debian.org/GrubEFIReinstall

I can't find any references to 'fw' and/or 'lvfs' in either:

/var/log/apt/history.log

or

/var/log/apt/term.log

but I believe that the Firmware update was this one:

https://fwupd.org/lvfs/device/ebfe8df8-dee7-4692-a721-cbcf5095c5cf

Lenovo ThinkPad T480s System Firmware Version 1.29.

this is the output of efibootmgr -v **after** reinstalling grub:

```
alex@polaris:~$ efibootmgr -v
BootCurrent: 0001
Timeout: 0 seconds
BootOrder: 0001,0000,0017,0018,0019,001A,001B,001C,001D,001E
Boot0000* Windows Boot Manager	HD(1,GPT,59ffb5ef-5281-43f9-87c9-2f08e31b9721,0x800,0x82000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}....................
Boot0001* debian	HD(1,GPT,59ffb5ef-5281-43f9-87c9-2f08e31b9721,0x800,0x82000)/File(\EFI\debian\grubx64.efi)
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0015  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0016  MEBx Hot Key	FvFile(ac6fd56a-3d41-4efd-a1b9-870293811a28)
Boot0017* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0018* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0019* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001A* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001B* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot001C* PCI LAN	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot001D  Other CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a35406)
Boot001E  Other HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f606)
Boot001F* USBR BOOT CDROM	PciRoot(0x0)/Pci(0x14,0x0)/USB(11,1)
Boot0020* USBR BOOT Floppy	PciRoot(0x0)/Pci(0x14,0x0)/USB(11,0)
Boot0021* ATA HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f6)
Boot0022* ATAPI CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a354)
Boot0023* PCI LAN	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
alex@polaris:~$
```

Thanks

**Comment by superm1** [comment]
Can you check your system journal for fwupd.service and share the logs from there?  It should have logged the boot entries from right befor the attempt.  It might be useful for the vendor to diagnose.

**Comment by asanchez1987** [comment]
The update was done 2 days ago, on Monday 18th. For whatever reason journalctl doesn't retrieve info since that date:

```
root@polaris:~# journalctl -u fwupd.service
-- Logs begin at Wed 2019-02-20 10:02:42 CET, end at Wed 2019-02-20 15:47:29 CET. --
Feb 20 10:03:33 polaris systemd[1]: Starting Firmware update daemon...
Feb 20 10:03:39 polaris systemd[1]: Started Firmware update daemon.
root@polaris:~# journalctl --since "2 days ago" -u fwupd.service
-- Logs begin at Wed 2019-02-20 10:02:42 CET, end at Wed 2019-02-20 15:47:29 CET. --
Feb 20 10:03:33 polaris systemd[1]: Starting Firmware update daemon...
Feb 20 10:03:39 polaris systemd[1]: Started Firmware update daemon.
root@polaris:~#
```

**Comment by yath** [comment]
Just as a +1, this also happened to me on my X1 Carbon Gen4. I don’t believe this is a problem in Lenovo’s firmware, as suggested in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922770#10, as the manual method did not ever clear my UEFI variables.

Could it be more likely that this is a bug in fwupd’s UEFI shim that - for whatever reasons - logs to efivars, which is known (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0389075ecfb6231818de9b0225d3a5a21a661171) to be dangerous? What is that shim even used for? IIUC, UEFI Update Capsules are supposed to be processed by the firmware itself, isn’t it?

**Comment by yath** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=919485 was the other efivars bug that I had in my mind. What were the considerations that led to logging to efivars in the first place?

**Comment by superm1** [comment]
I don't see any connection with writing a UEFI variable == remove all boot entries.  That kernel commit you linked was a firmware bug related to deleting all UEFI variables caused the system to not boot (firmware didn't automatically rebuild them).

The flow that fwupd uses is like this:
* Write out file to ESP
* Write out efi variable to efivars indicates what files are on ESP that should be used
* Write out new boot entry efi variable
* Write out new BootOrder efi variable
* Write out new BootNext efi variable
* Reboot system into fwupd.efi
* Look for efi variable pointing to a file.
* Look for files indicated in EFI variable
* Remove added boot entry
* Pass payload to BIOS `UpdateCapsule()` method

There are many thousands of reports of successful firmware upgrades with LVFS with a variety of system manufacturers.  If the upgrade works but boot entries are missing after the upgrade it's firmly in the camp of it's a manufacturer BIOS bug.

**Comment by yath** [comment]
> I don't see any connection with writing a UEFI variable == remove all boot entries.

The boot entries are stored in such variables. And your UEFI payload is a) messing around with boot entries, and b) writing to other EFI variables for debugging, which may overwrite existing, other variables (like: the boot entries) in case of a firmware bug. Linux addressed this in 68d929862e29a8b52a7f2f2f86a0600423b093cd; the bugzilla Bug I linked has further examples of apparently broken hardware.

**Comment by yath** [comment]
> There are many thousands of reports of successful firmware upgrades with LVFS with a variety of system manufacturers.

Other data point: Since Sunday I have read about three people having their boot entries killed after applying a firmware upgrade.

> If the upgrade works but boot entries are missing after the upgrade it's firmly in the camp of it's a manufacturer BIOS bug.

You are probably right, but fwupd triggered that bug. Linux decided not to do so, rather than having Lenovo fix all firmware builds. I don’t see how “we tell Lenovo about this bug and until then claim we’ve done nothing wrong and let users have to repair their systems” is an advantage for the user. Case in point: I do love automatic firmware upgrades, but that very bug caused me to uninstall fwupd (heck, what will it even do to my NVMe disk?), hence I’m receiving no upgrades at all anymore.

**Comment by superm1** [comment]
OK I think we need to take a step back here.   The whole point of LVFS is to give a conduit to let vendors provide "safe" firmware upgrades to all Linux users.  If the firmware hasn't been properly validated then it isn't supposed to be promoted.
This firmware has multiple reports of problems, to me that means it should be demoted.  I hope that Lenovo is watching these issues, but I have no idea if they are.  If they're not then when @hughsie gets back from PTO he'll have to get in contact with them to demote these files and investigate whats wrong.

UEFI variables are the corner stone of many aspects of the UEFI specification.  Did you know that on every boot a monotonic counter EFI variable is incremented?  There are hundreds of variables that are provided through runtime services.
Just because a boot entry is created doesn't mean it's bad.  Just because something is logged doesn't mean it's bad.  Those are **basic** things that the spec explains how to do and supports.  If there is a firmware bug, it should be fixed in that firmware not tear out logging and modify the architecture of the capsule update to workaround that vendor's issue.

**Comment by yath** [comment]
I’m not going to argue with you on the technical side, my memories are too rusty.

But I do know that the only thing that changed between previous updates, that didn’t leave my system unbootable afterwards, and the last one, which did, is the use of fwupd. And frankly, I did not expect my system to boot into some little-tested C code after installing an update in the first place, so please apologize if I’m tempted to blame the new code.

**Comment by hughsie** [comment]
Could this be the breakage as fixed in 44ce5aeae4a07fc661ecf1fae37aaa073c4b881c perhaps?

**Comment by superm1** [comment]
I could certainly believe that to fix things.

**Comment by superm1** [comment]
To those on this thread who don't know the background, let me try to explain.

1. Before `fwupdate` was merged into `fwupd` (`fwupd` releases < `1.1.0`) the EFI boot entry was named `Linux-Firmware-Updater`.  It had dashes in the name due to a bug that was fixed in shim `10` (See commit https://github.com/rhboot/shim/commit/3322257e611e2000f79726d295bb4845bbe449e7)
2. In `fwupd` release `1.1.0` `fwupdate` was merged in and they were distributed as one.  The boot entry was renamed to `Linux Firmware Updater` as all the major distros now had shim `10`.  (See commit https://github.com/hughsie/fwupd/commit/14fad85164d70912b07bc1b896e40766b305ae33)
3. The Lenovo UEFI capsule implementation keys off of the string of the boot entry to determine that the capsule is being launched from Linux/fwupd.  This causes a difference in their capsule execution behavior.  Some versions of BIOS on some systems keyed off the string `Linux-Firmware-Updater` others key off either string.  I don't know what actually changes but hypothesize they might be doing something like _save_ and _restore_ boot entries only if you run the capsule update from Linux/fwupd.  Who knows, maybe they also do that if the boot entry is called `Windows Boot Manager`...
4. Because of this behavior this commit was added to fwupd https://github.com/hughsie/fwupd/commit/44ce5aeae4a07fc661ecf1fae37aaa073c4b881c to special case Lenovo systems in the 1.2.4 fwupd release to use the "old" `Linux-Firmware-Updater` string.  All other UEFI implementations use `Linux Firmware Updater`.

FWIW This bug was originally filed against fwupd 1.1.4, so that hack for Lenovo systems to use the old string was not present.

**Comment by yath** [comment]
Thanks for the update. One small detail (for my system specifically, don’t know about the OP): I’m not using the rhboot shim, I have Secure Boot disabled and are booting into a regular (UEFI) Grub2 and a regular Linux kernel.

Unfortunately, I can’t even tell what fwupdx64.efi I was using. I upgraded fwupd after applying the update, but before rebooting, from 1.1.4 to 1.2.4. So it might be possible that the boot entries initially were written with a 1.1.4 fwupd binary, but the actual shim loaded was a 1.2.4 one.

**Comment by superm1** [comment]
If that's the case you'll have the 1.1.4 generated entry. Can you rerun the update from 1.2.4 now? Just use allow reinstall flag with cab file as argument.

That should clarify if the Lenovo quirk fixes it.

**Comment by hughsie** [comment]
I think this is fixed now.
