### ISSUE TITLE
Show more detail on the public vendor list

### ISSUE THREAD

**Issue by hughsie** [fwupd/lvfs-website#391]
At the moment we just have a big table, with up to three tickmarks for:

* fwupd supported
* has account on LVFS
* is uploading firmware

I’d like to convert this giant table (which is getting bigger every week…) into one-card-per-vendor so that it matches the style of the rest of the site. This would also give us a bit more room to add other new per-vendor stats too.

This could be an an example of what I’d like to include:

* [tick] Hardware supported by fwupd (dfu, uefi)
* [tick] Createad account on LVFS on 2019-09-12 and now has 123 users
* [tick] Is acting as an ODM to another vendor.
* [tick] Has uploaded 123 firmware files for 45 different devices
* [tick] Manages 78 firmware for 9 different devices
* [tick] Has uploaded firmware recently (in the last 6 months)

I’m aware some of this might make the vendors uneasy, so feel free to shoot down ideas as required. My main worry is that there’s an ODM that just supplies one OEM, the firmware counts are going to be the same and thus it’ll be obvious the ODM→OEM relationship.  Other better ideas for per-vendor stats welcome too.

**Comment by superm1** [comment]
If there is a concern on leaking relationships like that I'd ask why are the numbers important on this page in the first place?

**Comment by hughsie** [comment]
I'm trying to make each vendor more than just a binary tick. At the moment a vendor with one .cab file that they uploaded 3 years ago is on par with the vendors with dozens of users and hundreds of firmwares.

**Comment by superm1** [comment]
> [tick] Hardware supported by fwupd (dfu, uefi)

I think specifically reporting the protocols supported will accomplish this.

>[tick] Createad account on LVFS on 2019-09-12 and now has 123 users

Eek, telling how many people in the company use LVFS?  I don't think that the general public should know a lot about this.  Especially since different vendors use it differently, one vendor might have one guy doing all the LVFS work and hundreds of firmwares with that being their full time job.  There might be another company with 100 people with LVFS accounts that don't accomplish the same results.

> I'm trying to make each vendor more than just a binary tick. At the moment a vendor with one .cab file that they uploaded 3 years ago is on par with the vendors with dozens of users and hundreds of firmwares.

I do think that the has uploaded firmware recently will help with that, I think that's a good idea.
